### ISSUE TITLE
兄弟，你训练12epoch with CBGS

### ISSUE THREAD

**Issue by WenxuanLi-whu** [VDIGPKU/HENet#3]
前7轮有没有采用objectSample策略啊，还有你这个配置4卡的4090估计要训练6天啊，有卡就是任性啊

**Comment by xiazhongyv** [comment]
没有使用ObjectSample，多摄相机数据还是比较难采样和粘贴的。
计算资源的话自动驾驶感知领域现状如此，4090还是显存太少了。我们的工作的一个贡献点也是在减少训练代价。作为参考，SparseBEV的v2-99版本模型，FP16需要70G显存，八卡A800训五六天。

**Comment by WenxuanLi-whu** [comment]
牛，能不能借a800让我用2周左右，我多帧图像点云融合有很大概率刷到前五，合作作者可以让你们3个名额怎么样，我也是slow-fast的套路，用4帧slow，12帧fast，我训练24e就可以了，训一次估计要2到3天

**Comment by xiazhongyv** [comment]
合作请邮件联系通讯作者，注明您的单位和具体合作内容，谢谢。

**Comment by WenxuanLi-whu** [comment]
那算了哈，我慢慢跑吧，我现在测试6e+CBGS，需要2天半。用半精度+checkpoint勉强可以跑起来
